version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Cloning the repository...
      - git clone --depth 1 https://github.com/backstage/backstage.git
      - echo Installing dependencies...
      - yarn install --immutable
      - echo Running TypeScript compiler...
      - yarn tsc
      - echo Building the backend...
      - yarn build:backend
      - echo Building the Docker image...
      - DOCKER_BUILDKIT=1 docker build -t backops .
      - docker tag backops:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/backops:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/backops:latest

artifacts:
  files:
    - '**/*'